# Generated by Django 4.2.13 on 2024-06-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discountroomrate',
            unique_together={('room_rate', 'discount')},
        ),
    ]
